// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api/api.proto

package go_micro_service_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6d5bbc959d58c0, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6d5bbc959d58c0, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6d5bbc959d58c0, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6d5bbc959d58c0, []int{3}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6d5bbc959d58c0, []int{4}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6d5bbc959d58c0, []int{5}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6d5bbc959d58c0, []int{6}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type OrderRequest struct {
	Item                 string   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Quantity             int32    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6d5bbc959d58c0, []int{7}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *OrderRequest) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type OrderResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Item                 string               `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Quantity             int32                `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6d5bbc959d58c0, []int{8}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderResponse) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *OrderResponse) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.service.api.Message")
	proto.RegisterType((*Request)(nil), "go.micro.service.api.Request")
	proto.RegisterType((*Response)(nil), "go.micro.service.api.Response")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.service.api.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.service.api.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.service.api.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.service.api.Pong")
	proto.RegisterType((*OrderRequest)(nil), "go.micro.service.api.OrderRequest")
	proto.RegisterType((*OrderResponse)(nil), "go.micro.service.api.OrderResponse")
}

func init() {
	proto.RegisterFile("proto/api/api.proto", fileDescriptor_ca6d5bbc959d58c0)
}

var fileDescriptor_ca6d5bbc959d58c0 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x52, 0xdd, 0x6a, 0x14, 0x31,
	0x14, 0x6e, 0x66, 0x7f, 0xba, 0x3d, 0xfe, 0x50, 0x63, 0x91, 0x25, 0xda, 0xba, 0x44, 0xd0, 0xf1,
	0x26, 0x5b, 0xd6, 0x2b, 0x6f, 0x84, 0xc5, 0x0b, 0xbd, 0x11, 0x65, 0xea, 0xad, 0x48, 0xba, 0x73,
	0x0c, 0xc1, 0xcd, 0x64, 0x9a, 0x64, 0x85, 0xbe, 0x82, 0x0f, 0xe7, 0xeb, 0x78, 0x2b, 0x93, 0xc9,
	0x94, 0x55, 0x66, 0xd7, 0x07, 0xe8, 0x45, 0xe0, 0x1c, 0xbe, 0x1f, 0xf2, 0xf1, 0x1d, 0x78, 0x58,
	0x3b, 0x1b, 0xec, 0x5c, 0xd6, 0xba, 0x79, 0x22, 0x6e, 0xf4, 0x44, 0x59, 0x61, 0xf4, 0xca, 0x59,
	0xe1, 0xd1, 0xfd, 0xd0, 0x2b, 0x14, 0xb2, 0xd6, 0xec, 0xa9, 0xb2, 0x56, 0xad, 0x71, 0x1e, 0x39,
	0x97, 0x9b, 0x6f, 0xf3, 0xa0, 0x0d, 0xfa, 0x20, 0x4d, 0xdd, 0xca, 0xf8, 0x63, 0x38, 0xfc, 0x80,
	0xde, 0x4b, 0x85, 0xf4, 0x18, 0x06, 0x5e, 0x5e, 0x4f, 0xc9, 0x8c, 0xe4, 0x47, 0x45, 0x33, 0xf2,
	0x53, 0x38, 0x2c, 0xf0, 0x6a, 0x83, 0x3e, 0x50, 0x0a, 0xc3, 0x4a, 0x1a, 0x4c, 0x68, 0x9c, 0xf9,
	0x13, 0x98, 0x14, 0xe8, 0x6b, 0x5b, 0xf9, 0x28, 0x36, 0x5e, 0x75, 0x62, 0xe3, 0x15, 0xcf, 0xe1,
	0xf8, 0x22, 0x38, 0x94, 0x46, 0x57, 0xaa, 0x73, 0x39, 0x81, 0xd1, 0xca, 0x6e, 0xaa, 0x10, 0x79,
	0x83, 0xa2, 0x5d, 0xf8, 0x4b, 0x78, 0xb0, 0xc5, 0x4c, 0x86, 0xfd, 0xd4, 0x33, 0x18, 0x7e, 0xd2,
	0x95, 0xa2, 0x8f, 0x60, 0xec, 0x83, 0xb3, 0xdf, 0x31, 0xc1, 0x69, 0x8b, 0xb8, 0xdd, 0x83, 0xbf,
	0x81, 0xbb, 0x1f, 0x5d, 0x89, 0x6e, 0x2b, 0x96, 0x0e, 0x68, 0xba, 0x58, 0xcd, 0x4c, 0x19, 0x4c,
	0xae, 0x36, 0xb2, 0x0a, 0x3a, 0x5c, 0x4f, 0xb3, 0x19, 0xc9, 0x47, 0xc5, 0xcd, 0xce, 0x7f, 0x12,
	0xb8, 0x97, 0x0c, 0xd2, 0x3f, 0xef, 0x43, 0xa6, 0xcb, 0xa4, 0xcf, 0x74, 0x79, 0xe3, 0x98, 0xed,
	0x70, 0x1c, 0xfc, 0xed, 0x48, 0x5f, 0x03, 0xac, 0x1c, 0xca, 0x80, 0xe5, 0x57, 0x19, 0xa6, 0xc3,
	0x19, 0xc9, 0xef, 0x2c, 0x98, 0x68, 0x6b, 0x13, 0x5d, 0x6d, 0xe2, 0x73, 0x57, 0x5b, 0x71, 0x94,
	0xd8, 0xcb, 0xb0, 0xf8, 0x4d, 0x60, 0xb0, 0xac, 0x35, 0x7d, 0x07, 0xc3, 0xb7, 0x72, 0xbd, 0xa6,
	0xa7, 0xa2, 0xef, 0x06, 0x44, 0xca, 0xca, 0xce, 0x76, 0xc1, 0x6d, 0x12, 0x7e, 0x40, 0xbf, 0xc0,
	0xb8, 0x2d, 0x82, 0x3e, 0xef, 0xe7, 0xfe, 0x5b, 0x28, 0x7b, 0xf1, 0x5f, 0x5e, 0x67, 0x7e, 0x4e,
	0xe8, 0x7b, 0x98, 0x34, 0xe5, 0xc5, 0x82, 0x58, 0xbf, 0xb0, 0xc1, 0xd9, 0x2e, 0xcc, 0x56, 0x8a,
	0x1f, 0xe4, 0xe4, 0x9c, 0x2c, 0x7e, 0x65, 0x30, 0x8a, 0x35, 0xdc, 0xbe, 0xec, 0xf4, 0x02, 0x26,
	0xcb, 0xb2, 0x6c, 0xd3, 0xf3, 0x7e, 0xf6, 0xf6, 0x89, 0xb3, 0x67, 0x7b, 0x39, 0xed, 0x17, 0x2f,
	0xc7, 0xf1, 0xd2, 0x5e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x44, 0x6a, 0xc4, 0x5b, 0x04,
	0x00, 0x00,
}
