// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/packaging/packaging.proto

package go_micro_service_packaging

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Packaging service

type PackagingService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Packaging_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Packaging_PingPongService, error)
}

type packagingService struct {
	c    client.Client
	name string
}

func NewPackagingService(name string, c client.Client) PackagingService {
	return &packagingService{
		c:    c,
		name: name,
	}
}

func (c *packagingService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Packaging.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagingService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Packaging_StreamService, error) {
	req := c.c.NewRequest(c.name, "Packaging.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &packagingServiceStream{stream}, nil
}

type Packaging_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type packagingServiceStream struct {
	stream client.Stream
}

func (x *packagingServiceStream) Close() error {
	return x.stream.Close()
}

func (x *packagingServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *packagingServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *packagingServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *packagingServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *packagingService) PingPong(ctx context.Context, opts ...client.CallOption) (Packaging_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Packaging.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &packagingServicePingPong{stream}, nil
}

type Packaging_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type packagingServicePingPong struct {
	stream client.Stream
}

func (x *packagingServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *packagingServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *packagingServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *packagingServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *packagingServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *packagingServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Packaging service

type PackagingHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Packaging_StreamStream) error
	PingPong(context.Context, Packaging_PingPongStream) error
}

func RegisterPackagingHandler(s server.Server, hdlr PackagingHandler, opts ...server.HandlerOption) error {
	type packaging interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Packaging struct {
		packaging
	}
	h := &packagingHandler{hdlr}
	return s.Handle(s.NewHandler(&Packaging{h}, opts...))
}

type packagingHandler struct {
	PackagingHandler
}

func (h *packagingHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.PackagingHandler.Call(ctx, in, out)
}

func (h *packagingHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PackagingHandler.Stream(ctx, m, &packagingStreamStream{stream})
}

type Packaging_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type packagingStreamStream struct {
	stream server.Stream
}

func (x *packagingStreamStream) Close() error {
	return x.stream.Close()
}

func (x *packagingStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *packagingStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *packagingStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *packagingStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *packagingHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.PackagingHandler.PingPong(ctx, &packagingPingPongStream{stream})
}

type Packaging_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type packagingPingPongStream struct {
	stream server.Stream
}

func (x *packagingPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *packagingPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *packagingPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *packagingPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *packagingPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *packagingPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
