// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/shipping/shipping.proto

package go_micro_service_shipping

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Shipping service

type ShippingService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Shipping_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Shipping_PingPongService, error)
}

type shippingService struct {
	c    client.Client
	name string
}

func NewShippingService(name string, c client.Client) ShippingService {
	return &shippingService{
		c:    c,
		name: name,
	}
}

func (c *shippingService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Shipping.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Shipping_StreamService, error) {
	req := c.c.NewRequest(c.name, "Shipping.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &shippingServiceStream{stream}, nil
}

type Shipping_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type shippingServiceStream struct {
	stream client.Stream
}

func (x *shippingServiceStream) Close() error {
	return x.stream.Close()
}

func (x *shippingServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *shippingServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shippingServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shippingServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shippingService) PingPong(ctx context.Context, opts ...client.CallOption) (Shipping_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Shipping.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &shippingServicePingPong{stream}, nil
}

type Shipping_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type shippingServicePingPong struct {
	stream client.Stream
}

func (x *shippingServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *shippingServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *shippingServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shippingServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shippingServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *shippingServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Shipping service

type ShippingHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Shipping_StreamStream) error
	PingPong(context.Context, Shipping_PingPongStream) error
}

func RegisterShippingHandler(s server.Server, hdlr ShippingHandler, opts ...server.HandlerOption) error {
	type shipping interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Shipping struct {
		shipping
	}
	h := &shippingHandler{hdlr}
	return s.Handle(s.NewHandler(&Shipping{h}, opts...))
}

type shippingHandler struct {
	ShippingHandler
}

func (h *shippingHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ShippingHandler.Call(ctx, in, out)
}

func (h *shippingHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ShippingHandler.Stream(ctx, m, &shippingStreamStream{stream})
}

type Shipping_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type shippingStreamStream struct {
	stream server.Stream
}

func (x *shippingStreamStream) Close() error {
	return x.stream.Close()
}

func (x *shippingStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *shippingStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shippingStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shippingStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *shippingHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ShippingHandler.PingPong(ctx, &shippingPingPongStream{stream})
}

type Shipping_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type shippingPingPongStream struct {
	stream server.Stream
}

func (x *shippingPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *shippingPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *shippingPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shippingPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shippingPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *shippingPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
