// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/order/order.proto

package go_micro_service_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Order service

type OrderService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Order_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Order_PingPongService, error)
	AddOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Order_StreamService, error) {
	req := c.c.NewRequest(c.name, "Order.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &orderServiceStream{stream}, nil
}

type Order_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type orderServiceStream struct {
	stream client.Stream
}

func (x *orderServiceStream) Close() error {
	return x.stream.Close()
}

func (x *orderServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *orderServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *orderServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *orderServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderService) PingPong(ctx context.Context, opts ...client.CallOption) (Order_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Order.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &orderServicePingPong{stream}, nil
}

type Order_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type orderServicePingPong struct {
	stream client.Stream
}

func (x *orderServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *orderServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *orderServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *orderServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *orderServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *orderServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderService) AddOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "Order.AddOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Order service

type OrderHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Order_StreamStream) error
	PingPong(context.Context, Order_PingPongStream) error
	AddOrder(context.Context, *OrderRequest, *OrderResponse) error
}

func RegisterOrderHandler(s server.Server, hdlr OrderHandler, opts ...server.HandlerOption) error {
	type order interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
		AddOrder(ctx context.Context, in *OrderRequest, out *OrderResponse) error
	}
	type Order struct {
		order
	}
	h := &orderHandler{hdlr}
	return s.Handle(s.NewHandler(&Order{h}, opts...))
}

type orderHandler struct {
	OrderHandler
}

func (h *orderHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.OrderHandler.Call(ctx, in, out)
}

func (h *orderHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.OrderHandler.Stream(ctx, m, &orderStreamStream{stream})
}

type Order_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type orderStreamStream struct {
	stream server.Stream
}

func (x *orderStreamStream) Close() error {
	return x.stream.Close()
}

func (x *orderStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *orderStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *orderStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *orderStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *orderHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.OrderHandler.PingPong(ctx, &orderPingPongStream{stream})
}

type Order_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type orderPingPongStream struct {
	stream server.Stream
}

func (x *orderPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *orderPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *orderPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *orderPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *orderPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *orderPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *orderHandler) AddOrder(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderHandler.AddOrder(ctx, in, out)
}
